### PR TITLE
Fix for Teclast F5 DSDT Tables

### PR DESCRIPTION
**Pull request by ijonglin**
Series of DSDT implementations to fix S3 issues.   Merged the current broken DSDT F5 with the Teclast F7 Plus DSDT that works out of the box.

### CODE REVIEW

**Comment by Kabbone** [comment]
I can confirm, that this DSDT table fixes the wakeup problems of touchpad and keyboard, but S3 is still only working with deavtivated S0ix and thus no touchscreen.
The problem why your initrd load of the table doesn't work is simple, you didn't increase the Revision number, this is necessary if it should override the BIOS one.

Thanks for the work :), you repository is the only solution I found so far.

**Comment by ijonglin** [comment]
@Kabbone Excellent.  I'll guess I'll merge it then.  Would love to have follow-up discussion on making this arch-independent, instead of Ubuntu-centric.   Also, is the only bug that I forgot to force the revision number upgrade on the DSDT compile?  I can fix that, and then I'll merge this branch to master.

BTW, it's been working perfectly on two Teclast F5's for the last year or so that I purchased over the Internet (with touchscreen and everything).   One of the BIOS settings may be the issue.  Disable EC Notification in the ACPI power screen and things might all just work.

**Comment by Kabbone** [comment]
For loading the file per initrd, yes this should be the only bug as long as the kernel is compiled with ACPI_TABLE_UPGRADE. Like this I was able to load and override my table with:
OS: Arch Linux
Kernel: 5.6.4
Bootloader: systemd-boot

Unfortunately I'm still struggling with the S0ix and I'm a bit confused. I did a side-by-side comparison of enabled and disabled with acpidump. The only differences are in facp and facs, I will take a closer look to this tomorrow.
I also had a weird bug today, I wasn't able to turn it on again without plugin in the power cable, but after a BIOS default reset everything worked as before.

Just for notice: I'm not too familiar with the in-depth of ACPI, but trying to get a better understanding of it.

**Comment by ijonglin** [comment]
@Kabbone Bumped the revision number.  Let me know whether everything works out of the box.  On my next revision, I will try to document the ACPI_TABLE_UPGRADE path.  With the version of the kernel that I've tested, everything is working for me: mouse, touchscreen, keyboard  -- it' has had up an time of 80 hours without any issues waking from sleep.   I was able to use that kernel on another Teclast F5 with the same goodness.

Ah per initrd, never was able to get that to work.  Once you okay this revision bump, I'll merge and try to document the initrd steps.

The reboot thing happens occasionally and may or may not be related to the fix
One of the BIOS settings that really seems to mess with the keyboard/mouse/touchpad is the EC Notification.  Turn that off in the BIOS and you may have everything you need.   You are running off of a much newer version of the kernel, so your mileage may vary.

I gave up on S0ix -- it was never able to drop into C10 low power state (which is prerequisite for S0ix), so you never get the power savings you would like.  Even when it's on and I put the machine to sleep, it was still drawing 2-3 Watts, which was pretty pointless.   S3 works though, and when the keyboard and mouse come back, and pretty darn happy.   The other thing I did was replace the 26.6 Wh battery with a 41Wh one, but that was a massive physical hack -- but it does last 8 hours now.  Just had to run the risk of Lithium Ion fires, and clearly I can never bring it on a plane.  But it goes 4-5 on full power, and with S3 sleep that works out just fine.

**Comment by ijonglin** [comment]
@Kabbone Also, looking at my old notes, turning off S0ix seems to make the touchscreen work.

**Comment by Kabbone** [comment]
yeah, I saw that before and with S0ix disabled everything works as expected with the new acpi table.
Unfortunately disabling the EC Notification didn't do much for the S0ix and touchscreen problem, but 2-3W would be really pointless, with display and wlan off I should already be at 2W or even below without S0ix.
Checked the pull request #3 and works for me with this small change

**Comment by ijonglin** [comment]
FYI, just upgraded my two F5 laptops to Ubuntu 20.04 and it all works with
only the change to the DSDT Table.   I'm going to be switching jobs soon,
so I'll update the page when I got some downtime.

Cheers,
I-Jong

**Pull request merged**
